name: Feature request
description: Suggest an improvement or new capability
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What would you like to see?
      placeholder: Briefly describe the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: What problem does this solve, and who benefits?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Note any workarounds or related ideas.
